### PR TITLE
Segmented-control, Checkbox-group, and Radio-button-group: fixes the font-size of the label, and adds required prop

### LINKED ISSUE #1963: Segmented-control, Checkbox-group, and Radio-button group: fix the font-size of the label
### Detailed description of how to reproduce the problem

The font-size of the label is incorrect. It must be like the font-size of ifx-select and text-field. 

### Upload a screenshot

Image

### Describe the development framework

Any

### Expected behavior

Font-size of the label should be like the ifx-select and ifx-text-field

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by evangeliaPanteliadou**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

### Example apps
- adds **segmented-control** to the Vanilla example app
- adds **text-field** to the React example app
### General enhancements
- replaces hardcoded CSS property values with **ifx-tokens**
### Design alignment
- aligns label/caption font across **segmented-control,** **checkbox-group,** **radio-button-group** to match text-field
- adjusts **segmented-control** spacing to align with text-field
### Bugs
- fixes bug in **text-field** component where the disabled class was added to the caption element even when disabled was false
### Added features
- adds required and error props to the **segmented-control** component
- adds required prop to the **radio-button-group** and **checkbox-group**
### Tests
- adds tests for required prop to the **radio-button-group,** **checkbox-group,** and **segmented-control**

Related Issue
#1963 

<details>
  <summary>📦 Published PR as canary version: <code>38.2.0--canary.1964.07f4267301a9e98cecb20befa69a9cbe4d970f79.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@38.2.0--canary.1964.07f4267301a9e98cecb20befa69a9cbe4d970f79.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@38.2.0--canary.1964.07f4267301a9e98cecb20befa69a9cbe4d970f79.0
  ```
</details>

### CODE REVIEW

File: packages/components/src/components/segmented-control/segmented-control.tsx [hunk 1]
```diff
@@ -83,9 +86,10 @@ export class SegmentedControl {
 
     render() {
         return (
-            <div aria-value={this.selectedValue} aria-label='segmented control' class='group'>
+            <div aria-value={this.selectedValue} aria-label='segmented control' class={`group ${this.error ? 'error' : ''} ${this.required ? 'required' : ''}`}>
```
Comment (tishoyanchev) [inline packages/components/src/components/segmented-control/segmented-control.tsx:89]: Why are you conditionally setting the error and required classes on the group element?

**Comment by tishoyanchev** [comment]
@evangeliaPanteliadou 
- required asterisk shows up even without label on segmented controls, checkbox-group and radio-group
- why add font family to segmented controls?

**Comment by evangeliapant** [comment]
@tishoyanchev 

I couldn't reproduce the issue with the required asterisk showing up without a label on the checkbox-group and radio-group components. I'm not sure where you encountered it, but when running the branch locally, both components work as expected.

The only issue I could confirm is with the segmented control, where the asterisk is not dependent on the label. This happens because the label prop on that component isn't a boolean, so the asterisk logic doesn't currently check for it.
